// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNoj0pPQlJrM9ZmkbRzFku1bYafllzTf0',
    appId: '1:686670075977:web:772124be78ee669810c798',
    messagingSenderId: '686670075977',
    projectId: 'fir-9c890',
    authDomain: 'fir-9c890.firebaseapp.com',
    storageBucket: 'fir-9c890.firebasestorage.app',
    measurementId: 'G-GS02FZ6NM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlcUlrDsWuLLC-Ex9tqKg7VXJVglylduM',
    appId: '1:686670075977:android:4e4706a1086b45b410c798',
    messagingSenderId: '686670075977',
    projectId: 'fir-9c890',
    storageBucket: 'fir-9c890.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgJdoe4YGD5ilf-5PItu55ehwAnpyI03I',
    appId: '1:686670075977:ios:51bea4de6c53a0a710c798',
    messagingSenderId: '686670075977',
    projectId: 'fir-9c890',
    storageBucket: 'fir-9c890.firebasestorage.app',
    iosBundleId: 'com.example.fFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgJdoe4YGD5ilf-5PItu55ehwAnpyI03I',
    appId: '1:686670075977:ios:51bea4de6c53a0a710c798',
    messagingSenderId: '686670075977',
    projectId: 'fir-9c890',
    storageBucket: 'fir-9c890.firebasestorage.app',
    iosBundleId: 'com.example.fFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNoj0pPQlJrM9ZmkbRzFku1bYafllzTf0',
    appId: '1:686670075977:web:8b6b218165148aa110c798',
    messagingSenderId: '686670075977',
    projectId: 'fir-9c890',
    authDomain: 'fir-9c890.firebaseapp.com',
    storageBucket: 'fir-9c890.firebasestorage.app',
    measurementId: 'G-0CVRZVGHCQ',
  );
}
