// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBibIwdsmS5VqWZ8tkZa0Y_oZc6YU_l_b4',
    appId: '1:543638889276:web:beda4ff7d1c94d8b103439',
    messagingSenderId: '543638889276',
    projectId: 'chefs-arena-ac09d',
    authDomain: 'chefs-arena-ac09d.firebaseapp.com',
    storageBucket: 'chefs-arena-ac09d.firebasestorage.app',
    measurementId: 'G-M5SBRSNHZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAitmSaKqgOmLbv4vLdym9L4Adv9_rvfKg',
    appId: '1:543638889276:android:d2c28b674dac0c58103439',
    messagingSenderId: '543638889276',
    projectId: 'chefs-arena-ac09d',
    storageBucket: 'chefs-arena-ac09d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_s0ZuhvdD-JgDD8Eu4afy-kwyp6odkk',
    appId: '1:543638889276:ios:2b3dfe1a4e67715f103439',
    messagingSenderId: '543638889276',
    projectId: 'chefs-arena-ac09d',
    storageBucket: 'chefs-arena-ac09d.firebasestorage.app',
    iosBundleId: 'com.example.fChefsarena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT_s0ZuhvdD-JgDD8Eu4afy-kwyp6odkk',
    appId: '1:543638889276:ios:2b3dfe1a4e67715f103439',
    messagingSenderId: '543638889276',
    projectId: 'chefs-arena-ac09d',
    storageBucket: 'chefs-arena-ac09d.firebasestorage.app',
    iosBundleId: 'com.example.fChefsarena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBibIwdsmS5VqWZ8tkZa0Y_oZc6YU_l_b4',
    appId: '1:543638889276:web:514f20aa6b82e83e103439',
    messagingSenderId: '543638889276',
    projectId: 'chefs-arena-ac09d',
    authDomain: 'chefs-arena-ac09d.firebaseapp.com',
    storageBucket: 'chefs-arena-ac09d.firebasestorage.app',
    measurementId: 'G-XXRT22X8H5',
  );
}
